# Generated by Django 3.0.4 on 2020-03-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Elevenses', 'Elevenses'), ('Lunch', 'Lunch'), ('Tea', 'Tea'), ('Supper', 'Supper'), ('Dinner', 'Dinner')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
