# Generated by Django 3.0.4 on 2020-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_directions',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_final',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_ingredients',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
    ]
