# Generated by Django 3.0.4 on 2020-03-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_enjoy',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_final',
            field=models.ImageField(blank=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_directions',
            field=models.ImageField(blank=True, upload_to='recipes/images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_ingerdients',
            field=models.ImageField(blank=True, upload_to='recipes/images/'),
        ),
    ]
