# Generated by Django 3.0.4 on 2020-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200319_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_ingerdients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_ingredients',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
    ]
