# Generated by Django 3.0.4 on 2020-03-18 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200318_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Meal'),
        ),
    ]
