# Generated by Django 3.0.3 on 2020-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200318_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Elevenses', 'Elevenses'), ('Lunch', 'Lunch'), ('Tea', 'Tea'), ('Supper', 'Supper'), ('Dinner', 'Dinner')], max_length=100),
        ),
    ]
