# Generated by Django 3.0.4 on 2020-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200320_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='static/default_img.gif', upload_to='recipes/images/'),
        ),
    ]
