# Generated by Django 3.0.4 on 2020-03-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user.jpg', upload_to='recipes/users'),
        ),
    ]
