# Generated by Django 3.0.4 on 2020-03-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200321_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default_img.gif', upload_to='recipes/images/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
