# Generated by Django 3.0.4 on 2020-03-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20200321_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='recipes/images/'),
        ),
    ]
