# Generated by Django 3.0.4 on 2020-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20200322_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/default.png', upload_to='recipes/images/'),
        ),
    ]
